### ISSUE TITLE
[Discussion] Implement CODEOWNERS file

### ISSUE THREAD

**Issue by Evanito** [Nexus-Mods/vortex-games#20]
I propose implementing a CODEOWNERS file to involve the authors in their plugins' ongoing development. 

When making a Pull Request, the contributor can add themselves to the CODEOWNERS file and link themselves to the extension(s) they are adding. If any future PR changes these files, they will be automatically notified and requested for a review via GitHub. If they do not wish to be involved in the extensions' further development, they may choose to not add themselves as a codeowner for those files. 

Note that it does not give the code owners any extra permissions nor does it block normal usage.

In my opinion, this is in the interest of making this repository warmer to open source developers.

### More information:

https://github.blog/2017-07-06-introducing-code-owners/
https://help.github.com/articles/about-code-owners/

**Comment by TanninOne** [comment]
I didn't know about that feature yet but sounds good, I'll try it out

**Comment by AlexejheroYTB** [comment]
I second this idea. The file could contain the contributors for each game and their review would be requested if the files were edited in a pull request. Something like
```
game-oni/* @newman55
game-subnautica/* @AlexejheroYTB @cybercatgurrl
game-witcher/* @Evanito
```
This could go one of two ways
1. All new and old contributors are added by repo collaborators (like you, Tannin) or by themselves if they make a pull request, or
2. Collaborators add themselves in their future pull requests, but most people would not realise that this option exists and/or where the CODEOWNERS file is located. This isn't a very known feature of GitHub.

**Comment by TanninOne** [comment]
I've added the file: https://github.com/Nexus-Mods/vortex-games/blob/master/CODEOWNERS

Is there a way to check if it's working without actually making a PR?

**Comment by AlexejheroYTB** [comment]
Unfortunately I don't think there is.

**Comment by AlexejheroYTB** [comment]
Should I make a pull request to test this?

**Comment by TanninOne** [comment]
Wait, Evanitos PR was already open. So at least it required me to review it so it works at least partially.
Let me make a PR to subnautica BZ to verify you are requested to review as well.

**Comment by AlexejheroYTB** [comment]
#21

**Comment by AlexejheroYTB** [comment]
It seems that only you were requested for review, could it be that the top-most file match is used? In this case, `*` for all files (despite of what it says in the docs?)

**Comment by TanninOne** [comment]
The example in the blog post specifically says that the last match takes precedence

**Comment by AlexejheroYTB** [comment]
Yet, it seems to not be working as intended :thinking:

**Comment by TanninOne** [comment]
could you check again? I've changed a repo setting.

**Comment by AlexejheroYTB** [comment]
No-one was requested for review. It might just only work for people who have been added as collaborators to the repository. Check: can you manually request my review?

**Comment by TanninOne** [comment]
No, I can't find you in the request for review box. So just to verify: If you go to "Files changed" you don't get a "Review Changes" button in the top right (alongside "Diff settings")?

**Comment by AlexejheroYTB** [comment]
From my experience with pull request reviews, they can only be requested for repo collaborators, meaning that outside contributors can't get a review request. Nevertheless, contributors can still review, but that review will not impact any branch protection rules or pull request stats, it will just act like it's not even there (reviews from contributors can be spotted because the changes requested or changes approved symbol is black, instead of green/red)

**Comment by TanninOne** [comment]
Well, _that's_ not really a problem, we need a collaborator to merge the PR anyway but I thought the CODEOWNERS file was supposed to automate the process of requesting reviews. I thought the branch protection rules were maybe required to trigger the review request but that doesn't seem to be the case.
Not sure what else to try.

**Comment by AlexejheroYTB** [comment]
I thought that too. In the case that this is just for collaborators, this may not work with with this repo

**Comment by TanninOne** [comment]
Yeah, sorry, as far as I understand collaborators I can't make everyone collaborator who contributed a game extension.
But I can't find any mention that codeowners have to be collaborators anywhere.

**Comment by Evanito** [comment]
> The people you choose as code owners must have write permissions for the repository.

https://help.github.com/articles/about-code-owners/

My apologies, it seems this won't be a possible solution. Thank you for considering it.

**Comment by TanninOne** [comment]
Too bad, it was a nice idea. I don't understand why it would have this restriction.
