### ISSUE TITLE
Do you support external pull requests?

### ISSUE THREAD

**Issue by mcdonnelldean** [Nexus-Mods/vortex-games#3]
More of a hypothetical question for the whole org. For instance, looking over the code, adding skyrimVR looks like a simple thing to do, but at the same time I wanted to check if ye actually support external pull requests. I want to be mindful that there are non code reasons why things may not be added as soon as a game drops. 

I don't know the schedule for skyrimVR but it looks like if nobody got to it before tomorrow night GMT I could add it by copying SkyrimSE and updating all appropriate values.

**Comment by TanninOne** [comment]
We do happily accept external pull requests, though it does makes sense to ask before you spend any serious amount time on something, so we can let you know early if, for some reason, it doesn't make sense.

In the case of SkyrimVR we will add support ourselves. In the case of bethesda games a bit more work is necessary to support it properly. Adding a game to this repo adds "basic" support so the game gets discovered by Vortex, you can install/manage mods, profiles,....
To get more game-specific features like savegames, plugins, ... to be supported we do have to do a little extra in the respective extensions that implement those features (e.g. gamebryo-plugin-management)

**Comment by mcdonnelldean** [comment]
Makes sense, I had a further look through the code and see what you mean. Interestingly I went spelunking the extension functionality generally and it's pretty spiffy. I have some ideas for my own novel extensions I'll try when everything stabilizes a bit further. 

Thanks for the update, for now I'll focus my time on bug reports as I come across them, though so far with multiple games I haven't really had much issues, it's all fairly solid.
