### ISSUE TITLE
Provide nexusPageId for missing games

### ISSUE THREAD

**Issue by FayneAldan** [Nexus-Mods/vortex-games#41]
`nexusPageId` should be provided in the `details` field for the few games that have their value hardcoded in [`extensions/nexus_integration/util/convertGameId#nexusGameId()`](https://github.com/Nexus-Mods/Vortex/blob/ceb0b198cec438bfd51225ac726af9c98bccb9e2/src/extensions/nexus_integration/util/convertGameId.ts#L23-L29). [`skyrimse`](https://github.com/Nexus-Mods/vortex-games/blob/c92ab4715343dfd73fccee8a6f49112bf61f7922/game-skyrimse/index.js#L82), [`falloutnv`](https://github.com/Nexus-Mods/vortex-games/blob/c92ab4715343dfd73fccee8a6f49112bf61f7922/game-falloutnv/index.js#L72), and [`teso`](https://github.com/Nexus-Mods/vortex-games/blob/c92ab4715343dfd73fccee8a6f49112bf61f7922/game-teso/index.js#L45) already have the field provided, but not `skyrimvr` and `fallout4vr`.

**Comment by TanninOne** [comment]
Well yes, the TODO comment states exactly that, don't think we need a separate issue for that. Also, please use the issue tracker on the Nexus-Mods/Vortex repo, it's not really practical to track multiple.
